### ISSUE TITLE
Additional HMTL footer issue with Boost Campus v3.7-r4

### ISSUE THREAD

**Issue by lane-interactive** [moodleuulm/moodle-theme_boost_campus#89] opened 2020-07-11 06:29 UTC
Hello, I just upgraded 3.7.3 to 3.7.6. I also upgraded the Boost Campus theme to v3.7-r4.

This has created an issue with text I had in the Footer "Before BODY is closed" section. Normally I use this as a site footer but after updating Boost Campus theme to v3.7-r4 the text from this region now is now stuck between/behind the navdrawer and page content. See image. Please let me know how to revert to previous version until resolved?

![image](https://user-images.githubusercontent.com/7983500/87218170-a68ba580-c393-11ea-9919-bf6204481269.png)

**Comment by RouvenTU** [comment] 2020-07-30 10:39
Hi,

we have the same issue and we solved it by copying {{{ output.standard_end_of_body_html }}} back to footer.mustache from columns2.mustache. It works for now but a fix would be nice. :) 

Kind Regards

Rouven

**Comment by lane-interactive** [comment] 2020-08-15 06:03
Thanks for your help Rouven! Yes a patch fix would be great.

**Comment by Kathrin84** [comment] 2020-08-26 06:12
Hello @webpedagogy,

thank you very much for this issue. We changed the displaying of this variable because we thought we would fix a JavaScript behat issue we were thinking about for very long time.
This regression was not intended, of course.

@RouvenTU, thank you very much for your proposal to fix this issue.
However, just moving the variable back to the footer fixes only the visble aspect but brings back the Behat issue. 
So I invested a lot time again and did some extended research.

After this, we did a larger redesign of the layout files and could get rid ob the Cache solution we implemented:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/40172a867ddbdf686d4ed5b71302fd65fa71cb48

The fix is applied on the current master branch (3.8+ version of Boost Campus).
You can try to backport this patch to your 3.7+ Boost Campus version, but at your own risk. :) Or you stay with just with your lightweight patch as the problems with the Behat tests do not affect a productive instance.

As this is fixed, I'll close this issue.

Best, Kathrin

**Closed as completed** 2020-08-26 06:15 UTC
Labels: bug, fixed, regression
