### ISSUE TITLE
footer blocks right side on app

### ISSUE THREAD

**Issue by jmd87fr** [moodleuulm/moodle-theme_boost_campus#79] opened 2020-03-09 08:14 UTC
Hi,
I use campus theme on a Moodle 3.8.1+ (Build: 20200306 and a desktop 3.8
I have some blocks in the footer 
With desktop app and with mobile app on tablet I have some touble (not with app and smatphone or web browser)
in the front page and in courses they are NoOK (blocks are at the right side)
In my dashboard they are ok (blocks are at the bottom of page)

Do you have some idéeas to fix it  ?
Thanks

**Comment by Kathrin84** [comment] 2020-08-28 08:32
Hi @jmd87fr ,

thank you very much for raising this issue and sorry for the really late response. COVID-19 pandemic mixed up a lot of things and made it impossible to deal with Boost Campus earlier.

I'm not quite sure if you are really talking about the real Apps Moodle is providing or if you are acting on the the web version on different devices.

To get a better impression, could you provide some screenshots?

I have an idea in mind what the cause might be, but I'm irritated when you say that it works with the app on the smartphone but not on the tablet.

With some screenshots I hopefully can see a little bit clearer.

Thanks in advance and best, Kathrin

**Comment by abias** [comment] 2021-03-13 21:22
I close this issue as there was no further feedback.

**Closed as completed by abias** 2021-03-13 21:22 UTC
