### ISSUE TITLE
Log in page background image disappears at lower browser window widths

### ISSUE THREAD

**Issue by rolandsherwood2** [moodleuulm/moodle-theme_boost_campus#18] opened 2018-02-08 04:14 UTC
When login page background images have been uploaded via the 'Design Settings' tab, reducing the the log in page width during viewing or viewing the log-in page on reduced width devices e.g. phones and tablets causes the background image to disappear. For us, this occurs whether using the 'Login form' option or not. System information: Moodle 3.3.4 (build: 20180115), Boost Campus 3.3-r3 (version: 2018020700).

**Comment by Kathrin84** [comment] 2018-02-08 06:32
Hi rolandsherwood2,
thanks for the report.
The behavior you described is not a bug but intended behavior. We do not load the background images on small devices for data reasons. This saves traffic for the mobile user and on such small screens the login field would overlap most of the image and so it's not really useful there.
I'll close this issue as this is not a bug.
Best, Kathrin

**Comment by abias** [comment] 2018-02-08 19:56
Hi all,

I think we could / should add this fact to https://github.com/moodleuulm/moodle-theme_boost_campus#login-page-background-images.

Thanks,
Alex

**Comment by abias** [comment] 2018-02-25 20:22
This has now been added by Kathrin to the README in b16a97cc4a55ee1ac7012c87684e50f7dbd0c379

**Closed as completed by abias** 2018-02-25 20:22 UTC
