### ISSUE TITLE
Wide tables lead to Footer/Header Design Problem

### ISSUE THREAD

**Issue by dnutzz** [moodleuulm/moodle-theme_boost_campus#78] opened 2020-02-20 10:55 UTC
Hey guys!

I found a design problem with wide tables. When table width exceeds the viewport width, the whole page is scrollable and therefore header/footer are not extended to the right (see attached screenshot). 

![grafik](https://user-images.githubusercontent.com/22622792/74927213-7ab55680-53d7-11ea-9cef-a0649c15c983.png)

Maybe it would be better to have horizontally scrollable tables by default?

**Comment by Kathrin84** [comment] 2020-02-21 07:15
Hi @dnutzz,

thank you very much for reporting this issue. 
However this is not a bug caused by this child theme, but a Boost core behavior. 
You added a screenshot from the Modle demo platform (demo.moodle.net) which is plain Moodle core.This behavior occurs in Boost Campus, too because it inherits from Boost. However the place to fix this, if even possible, is Moodle core in that case.

So I would recommend reporting this issue on tracker.moodle.org if there isn't an existing one yet.

As we cannot do anything here, we'll close this issue at that point.

Best, Kathrin

**Closed as completed by Kathrin84** 2020-02-21 07:15 UTC
