### ISSUE TITLE
Can't login after activating loginform

### ISSUE THREAD

**Issue by gushagelberg2** [moodleuulm/moodle-theme_boost_campus#47] opened 2018-11-28 11:01 UTC
After activating theme_boost_campus / loginform I could not longer login to my moodle site.
The features sets the login window to the left.
I had to change theme back to boost in the database and only then could I log back in.

Moodle Version: 3.5.3
Boost Campus Theme version 2018073100
Firefox 63

**Comment by Kathrin84** [comment] 2018-11-28 11:12
Hi @gushagelberg2,
thank you for raising this issue. However, it's a duplicate of issue #45 and has been fixed yesterday. Please update Boost Campus to v3.5-r3 and then the login should work fine again.
If not, please come back to me.
Best, Kathrin

**Closed as completed by Kathrin84** 2018-11-28 11:12 UTC
Labels: duplicate
