### ISSUE TITLE
Burger Menu overlaps content when using course format "grid"

### ISSUE THREAD

**Issue by ottorabo** [moodleuulm/moodle-theme_boost_campus#42] opened 2018-10-01 14:38 UTC
![boostcampus grid](https://user-images.githubusercontent.com/43753568/46295441-5796c680-c598-11e8-8e3f-e0df5c5c3511.png)

**Comment by abias** [comment] 2018-10-02 06:22
Hi @ottorabo,

thank you for your bug report. 

However, I am afraid that our support will only be limited here as this is a third-party course format and we have to check first if the course format is to blame for this behaviour or the theme.

Please do the following steps:
* Please check of this bug also happens on theme_boost (from Moodle core), not only on theme_boost_campus. I expect that the answer will be yes as theme_boost_campus does not change anything important like that with the nav drawer. If is only happens in theme_boost_campus, please report back here. If it also happens in theme_boost, theme_boost_campus is not to blame and we are done here, it's a incompatibility of theme_boost and format_grid then.
* Please report the bug also at the developer of format_grid on https://tracker.moodle.org/browse/CONTRIB-7270?jql=project%20%3D%20CONTRIB%20AND%20component%20%3D%20%22Course%20format%3A%20Grid%22. Gareth is a very active developer and should be able to check if he can solve this problem within his course format or tell you if this is intended behaviour.

Cheers,
Alex

**Comment by ottorabo** [comment] 2018-10-02 08:42
Hi Alex,

i tried the course format "grid" with the default boost theme and it works.
The content is displayed the on the topmost level:
![boost grid](https://user-images.githubusercontent.com/43753568/46338221-d68b0e00-c62f-11e8-96b1-09cd1cce4287.png)

**Comment by abias** [comment] 2018-10-02 11:23
Thank you, @ottorabo , for this additional screenshot. In this case, theme_boost_campus seems to be the culprit. We will have a look at that as soon as we have some free ressources, but please give us some days as this will only have lower priority.

**Comment by flodorantes** [comment] 2019-01-08 19:06
Hi, we have the same problems with boost campus and the grid course format. Do you know something about fixing the problem?
Thanks, Florian

**Comment by Kathrin84** [comment] 2019-11-13 09:58
Hi @ottorabo,

unfortunately we really could not allocate any resources to deal with this issue until now as the priority for bugs with 3rd party plugins that we do not use ourself is very low and we don't see any chance in the nearer future to be able work on this.

Nevertheless, if you would provide a pull request, we can offer to review it. Otherwise we are closing this issue at this point.

We're sorry to write this but we hope for your understanding.

Best, Kathrin

**Closed as completed by Kathrin84** 2019-11-13 09:58 UTC
