### ISSUE TITLE
Title position not vertical centered

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#3] opened 2017-08-09 08:45 UTC
It may be occurd only at us, maybe because of our logo, but if not, this is how to fix it:

We had the problem, that the title was not vertical centered within the navbar:
![mdl_logo_position_pre](https://user-images.githubusercontent.com/406414/29112630-c03b5884-7cee-11e7-9597-66b4a7d7d751.png)

We fixed this with:

```css
.navbar-light .navbar-brand.has-logo {
    color: #fff;
    margin-top: -0.2rem;
}
```

![mdl_logo_position_post](https://user-images.githubusercontent.com/406414/29112631-c03c13c8-7cee-11e7-896c-d0aea0c1e764.png)

**Comment by Kathrin84** [comment] 2017-08-09 11:07
Hi Sebastian,
thanks for your hint and solution proposal.
 Yes, I think this is because of the logo you used. I think I remember that I encountered something similar in my tests. However, we hesitated to implement such a correction, as we were not sure if it would look the same (centered) on all browsers and with different kind of logos and logo resolutions.
Could you try if the ```margin-top: -0,2rem``` works for different logos? If so, then we would love to improve the code with your proposal.
Thanks and cheers, Kathrin

**Comment by sennewood** [comment] 2017-08-09 11:27
I've tested the issue with a very high logo. The result looks like before:

![mdl_large_logo_test](https://user-images.githubusercontent.com/406414/29119430-66f255da-7d06-11e7-81bd-ce7c4d2fee6d.png)

**Comment by Kathrin84** [comment] 2017-09-07 06:07
Hi Sebastian,
I wanted to integrate a solution for this, but then I realised that the cause is settled in Boost core.
I would prefer to get it fixed there and not within this theme. I will close this issue and please you to do the adjustment within your own RAW SCSS (as you assumingly already did).
Best, Kathrin

Edit: 
Here's the tracker issue:
https://tracker.moodle.org/browse/MDL-60048

**Closed as completed by Kathrin84** 2017-09-07 06:07 UTC
