### ISSUE TITLE
File names break out of right sidebar 

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#7] opened 2017-08-23 09:55 UTC
In the sidebar on the right is this "My Files"-Box. We have the problem that the files names are to long for the box:

![mdlfiles](https://user-images.githubusercontent.com/406414/29610030-48f64246-87f9-11e7-88ba-dea9a5fb77ab.png)

**Comment by Kathrin84** [comment] 2017-08-25 07:38
Hi Sebastian,
is that occuring within Boost core, too? 
I could assume so, because I saw such boundary issues within the core theme already. I will take a look at it if I can solve it. 
Best, Kathrin

**Comment by sennewood** [comment] 2017-08-25 08:17
In Boost it looks fine:
![mdl_filename_boost](https://user-images.githubusercontent.com/406414/29705503-8dad7464-897e-11e7-9f53-8f8ef5d587b1.png)

**Comment by sennewood** [comment] 2017-08-29 08:27
### Fix:
```css
.block_private_files .ygtvchildren {
    white-space: normal;
}
```

**Comment by Kathrin84** [comment] 2017-08-30 08:56
Hi Sebastian,
you have to distinguish between filenames that contain white spaces or not. In your first screenshot, all long file names do not contain spaces, in your second one it contains some.
I could only reproduce the breaking out for filenames without spaces:
![meine_dateien](https://user-images.githubusercontent.com/4711883/29864003-b7ced598-8d71-11e7-8e5b-bee23e7d2a2e.png)

I did a fix for this and another problem with buttons with this commit:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/9dc722808f9aa21b8229e3655acdc212c8326076

Thanks for your solution proposal.

I'll close this issue. Best, Kathrin

**Closed as completed by Kathrin84** 2017-08-30 08:56 UTC

**Comment by sennewood** [comment] 2017-09-01 08:46
I made an official ticket for this issue: https://tracker.moodle.org/browse/MDL-60004
