### ISSUE TITLE
Theme breaks admin menu tabs

### ISSUE THREAD

**Issue by freeradicalx** [moodleuulm/moodle-theme_boost_campus#52] opened 2019-02-25 16:05 UTC
Upon switching Moodle's theme to Campus Boost, the tabs that divide up the admin page cease to function. The URL bar will still change to (For example) admin/search.php#linkcourses or admin/search.php#linkgrades, but the content of the page below no longer updates. We are attempting to apply this theme to a dev version of an active site, so there are other plugins in play that may complicate this issue and therefore this is more a request for troubleshooting suggestions than a full bug report. Any advice as to which Moodle js files handle tab switching and where to look for potential conflicts? Developer mode outputs no errors.

Thanks!

**Comment by Kathrin84** [comment] 2019-03-01 10:24
Hi @freeradicalx,

thank you for creating this issue.

Generally I would dare to doubt that the cause is Boost Campus itself. Not because Boost Campus cannot have bugs, of course, but because we did not do any changes for the administration pages in our child theme. So these pages are directly inherited from theme Boost core and it would be very likely that many other users and ourselves would face this problem then.

Nevertheless, I will give some hints for you to getting to the cause of the problem:
* As you said, the page changes are done with JavaScript. So please ensure that JS is active.
* You could switch to theme Boost Core and check if the problem also occurs with the core theme.
* For detecting JS errors, please have a look at the console (can be found in the dev tools of your browser). If there's a problem with any JS-file, it should be displayed there.
* As you said you are operating on a dev version as a clone of a productive instance where other plugins are also installed, you could deactivate one plugin after the other and check if the settings pages then work. So you could also identify which plugin causes the problem.

I hope this helps you to proceed with your debugging.

If you detect that Boost Campus itself causes the error, please come back and describe the cause that triggers the issue.

If you encounter that a JS of another plugin had side effects on the admin pages, it would be really nice if you could also come back here and give this short feedback so that this issue could be closed as "not a bug".

Best, Kathrin

**Comment by Kathrin84** [comment] 2019-05-31 07:34
Hi @freeradicalx,

as you did not respond anymore, I assume that this is not an issue anymore and therefore I'll close this issue.

If there are still problems, please don't hesitate to come back to us again.

Best, Kathrin

**Closed as completed by Kathrin84** 2019-05-31 07:34 UTC
