### ISSUE TITLE
Missing button "Turn editing on"

### ISSUE THREAD

**Issue by madvip3r** [moodleuulm/moodle-theme_boost_campus#95] opened 2020-09-11 11:26 UTC
Switching to theme Boost Campus has a consequence of disappearing of button "Turn editing on":

![Course_Tedenska_oblika_-_peskovnik_-_2020-09-11_09 21 10](https://user-images.githubusercontent.com/10324399/92919804-7020e400-f431-11ea-904b-5c2532326d1b.png)

It's not available in the menu:

![Course_Tedenska_oblika_-_peskovnik_-_2020-09-11_09 18 28](https://user-images.githubusercontent.com/10324399/92919856-87f86800-f431-11ea-99b2-e8231bfddbbc.png)

At default theme is normally visible: 

![Course_Tedenska_oblika_-_peskovnik_-_2020-09-11_09 23 41](https://user-images.githubusercontent.com/10324399/92919897-9d6d9200-f431-11ea-9d45-cadf5db0de5e.png)

**Comment by Kathrin84** [comment] 2020-09-14 06:06
Hi @madvip3r ,

thank you very much for raising this issue.

This is a duplicate of #87 and is fixed already on the master branch, but not yet released as a new 3.9-r1 version because some more work for this new version has to be done.

If you need the fix urgently, you can apply it on your Boost Campus instance. Otherwise I would ask you for some more patience. The new release will come in the nearer future.

Thanks and best, Kathrin

**Closed as completed** 2020-09-18 08:49 UTC
Labels: duplicate
