### ISSUE TITLE
Footer out of place in version 3.6 (Beta)

### ISSUE THREAD

**Issue by aguatacuperche** [moodleuulm/moodle-theme_boost_campus#46] opened 2018-11-21 10:24 UTC
In the new version 3.6 the footnote is out of place.

[Attachment screenshot](https://drive.google.com/open?id=1Aw5Km-kEkiA-uDsTARM2ZBgCVLNUuiId)

**Comment by Kathrin84** [comment] 2018-12-07 09:13
Hi @aguatacuperche,

thank you for raising this issue. So far, I did not have the chance to check Boost Campus for Moodle 3.6 due to everyday work overload and reduced capacities. 
Making Boost Campus ready for Moodle 3.6 is on our to-do list, of course. 
The cause might be that Moodle changed the footer and is using flexboxes now. The fix for this should not be difficult and will then be addressed in our 3.6 release.

Best, Kathrin

**Comment by rochelmeyer** [comment] 2019-01-06 13:10
The theme basically works, but the footer issue breaks functionality on some pages where input elements become unaccessible. Could it be a quick & dirty fix to set the footer to display:none until you find time to fix this?

**Comment by aguatacuperche** [comment] 2019-01-06 13:39
Hi @rochelmeyer

A few weeks ago we made the decision to upgrade to the new version 3.6.1. and we have returned to the original theme of Moodle (Boost). Unfortunately, we found more problems, especially in the new message system among other details. The Moodle roadmap explains that for the next update they will make other significant changes. Predictably, we would experience new setbacks again.

I have translated a large part of your theme into Spanish, that has been my contribution. However, we have abandoned Boost Campus.

Greetings, Enrique

**Comment by Kathrin84** [comment] 2019-01-31 11:52
Hi @aguatacuperche and @rochelmeyer,

this issue is fixed now and a 3.6 version of Boost Campus is released in the Moodle plugins repository (https://moodle.org/plugins/pluginversion.php?id=18853) Please update your instances.

So I'll close this issue.

Best, Kathrin

**Closed as completed by Kathrin84** 2019-01-31 11:52 UTC
Labels: bug, fixed
